### PR TITLE
TheDestroyer19's Suggestions

### PR DESCRIPTION
**Pull request by TheDestroyer19**
Here's a bunch of changes I would make. I've tried to include comments alongside the changes to explain why I made them. Feel free to browse through the commits

### CODE REVIEW

**Comment by Flaxoos** [comment]
Thanks @TheDestroyer19 
I actually already made some of the changes you described, would you mind rebasing and then reviewing the PR, leaving only comments that are still relevant?

**Comment by Flaxoos** [comment]
@TheDestroyer19 Also, could you do this on a branch? I prefer the git-flow / feature branch approach

**Comment by Flaxoos** [comment]
@TheDestroyer19 I manually added the fixes based on your PR
Please have another look and see if you still see issues
Thanks for your contribution

**Comment by TheDestroyer19** [comment]
Sorry I'm not going to be able to follow up on the issues.

**Pull request closed without merging**
